In [3]:
# Import the pandas library
import pandas as pd

# Define the path to your CSV file
file_path = r"C:\Users\admin\Downloads\dataset - 2020-09-24.csv"

foot_ball = pd.read_csv(r"C:\Users\admin\Downloads\dataset - 2020-09-24.csv")

# Display the first few rows of the DataFrame to verify the data
foot_ball.head()

,Name,Jersey Number,Club,Position,Nationality,Age,Appearances,Wins,Losses,Goals,...,Punches,High Claims,Catches,Sweeper clearances,Throw outs,Goal Kicks,Yellow cards,Red cards,Fouls,Offsides
0,Bernd Leno,1.0,Arsenal,Goalkeeper,Germany,28.0,64,28,16,0,...,34.0,26.0,17.0,28.0,375.0,489.0,2,0,0,NaN
1,Matt Macey,33.0,Arsenal,Goalkeeper,England,26.0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,NaN
2,Rúnar Alex Rúnarsson,13.0,Arsenal,Goalkeeper,Iceland,25.0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,NaN
3,Héctor Bellerín,2.0,Arsenal,Defender,Spain,25.0,160,90,37,7,...,NaN,NaN,NaN,NaN,NaN,NaN,23,0,125,8.0
4,Kieran Tierney,3.0,Arsenal,Defender,Scotland,23.0,16,7,5,1,...,NaN,NaN,NaN,NaN,NaN,NaN,2,0,9,0.0

In [4]:
# Display the last 7 rows of the DataFrame
foot_ball.tail(7)

,Name,Jersey Number,Club,Position,Nationality,Age,Appearances,Wins,Losses,Goals,...,Punches,High Claims,Catches,Sweeper clearances,Throw outs,Goal Kicks,Yellow cards,Red cards,Fouls,Offsides
564,Vitinha,20.0,Wolverhampton-Wanderers,Midfielder,Portugal,20.0,1,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
565,Meritan Shabani,57.0,Wolverhampton-Wanderers,Midfielder,Germany,21.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
566,Pedro Neto,7.0,Wolverhampton-Wanderers,Forward,Portugal,20.0,31,14,7,3,...,NaN,NaN,NaN,NaN,NaN,NaN,3,0,16,5.0
567,Raúl Jiménez,9.0,Wolverhampton-Wanderers,Forward,Mexico,29.0,78,32,23,32,...,NaN,NaN,NaN,NaN,NaN,NaN,7,0,81,52.0
568,Adama Traoré,37.0,Wolverhampton-Wanderers,Forward,Spain,24.0,105,27,47,5,...,NaN,NaN,NaN,NaN,NaN,NaN,4,0,80,13.0
569,Fábio Silva,17.0,Wolverhampton-Wanderers,Forward,Portugal,18.0,1,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0
570,Leonardo Campana,30.0,Wolverhampton-Wanderers,Forward,Ecuador,20.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0

In [5]:
# Access and display the "Nationality" and "Club" columns for all players
foot_ball[['Nationality', 'Club']]

    Nationality                     Club
0       Germany                  Arsenal
1       England                  Arsenal
2       Iceland                  Arsenal
3         Spain                  Arsenal
4      Scotland                  Arsenal
..          ...                      ...
566    Portugal  Wolverhampton-Wanderers
567      Mexico  Wolverhampton-Wanderers
568       Spain  Wolverhampton-Wanderers
569    Portugal  Wolverhampton-Wanderers
570     Ecuador  Wolverhampton-Wanderers

[571 rows x 2 columns]

In [6]:
# Access and display the data for the tenth player in the dataset using row index
tenth_player = foot_ball.iloc[9]  # Index is 9 because indexing starts at 0
print(tenth_player)

Name                      Calum Chambers
Jersey Number                       21.0
Club                             Arsenal
Position                        Defender
Nationality                      England
Age                                 25.0
Appearances                          139
Wins                                  47
Losses                                57
Goals                                  6
Goals per match                      NaN
Headed goals                         1.0
Goals with right foot                4.0
Goals with left foot                 1.0
Penalties scored                     NaN
Freekicks scored                     NaN
Shots                                NaN
Shots on target                      NaN
Shooting accuracy %                  NaN
Hit woodwork                         1.0
Big chances missed                   NaN
Clean sheets                        28.0
Goals conceded                     170.0
Tackles                            257.0
Tackle success %                     70%
Last man tackles                     1.0
Blocked shots                       22.0
Interceptions                      247.0
Clearances                         537.0
Headed Clearance                   301.0
Clearances off line                  1.0
Recoveries                         735.0
Duels won                          703.0
Duels lost                         619.0
Successful 50/50s                   93.0
Aerial battles won                 301.0
Aerial battles lost                240.0
Own goals                            1.0
Errors leading to goal               1.0
Assists                                3
Passes                              5935
Passes per match                    42.7
Big chances created                  9.0
Crosses                            210.0
Cross accuracy %                     18%
Through balls                        4.0
Accurate long balls                304.0
Saves                                NaN
Penalties saved                      NaN
Punches                              NaN
High Claims                          NaN
Catches                              NaN
Sweeper clearances                   NaN
Throw outs                           NaN
Goal Kicks                           NaN
Yellow cards                          28
Red cards                              1
Fouls                                137
Offsides                             2.0
Name: 9, dtype: object

In [7]:
# Access and display the data for the tenth player in the dataset using row index
tenth_player = foot_ball.iloc[9]  # Index 9 corresponds to the tenth player
tenth_player

Name                      Calum Chambers
Jersey Number                       21.0
Club                             Arsenal
Position                        Defender
Nationality                      England
Age                                 25.0
Appearances                          139
Wins                                  47
Losses                                57
Goals                                  6
Goals per match                      NaN
Headed goals                         1.0
Goals with right foot                4.0
Goals with left foot                 1.0
Penalties scored                     NaN
Freekicks scored                     NaN
Shots                                NaN
Shots on target                      NaN
Shooting accuracy %                  NaN
Hit woodwork                         1.0
Big chances missed                   NaN
Clean sheets                        28.0
Goals conceded                     170.0
Tackles                            257.0
Tackle success %                     70%
Last man tackles                     1.0
Blocked shots                       22.0
Interceptions                      247.0
Clearances                         537.0
Headed Clearance                   301.0
Clearances off line                  1.0
Recoveries                         735.0
Duels won                          703.0
Duels lost                         619.0
Successful 50/50s                   93.0
Aerial battles won                 301.0
Aerial battles lost                240.0
Own goals                            1.0
Errors leading to goal               1.0
Assists                                3
Passes                              5935
Passes per match                    42.7
Big chances created                  9.0
Crosses                            210.0
Cross accuracy %                     18%
Through balls                        4.0
Accurate long balls                304.0
Saves                                NaN
Penalties saved                      NaN
Punches                              NaN
High Claims                          NaN
Catches                              NaN
Sweeper clearances                   NaN
Throw outs                           NaN
Goal Kicks                           NaN
Yellow cards                          28
Red cards                              1
Fouls                                137
Offsides                             2.0
Name: 9, dtype: object

In [8]:
# Access and display the "Goals" and "Appearances" for players with index positions 100 to 110
selected_players = foot_ball.iloc[100:111][['Goals', 'Appearances']]
selected_players

     Goals  Appearances
100      1           35
101      1            1
102      0            0
103      0            0
104      8          264
105      7           96
106      0           11
107      5           61
108      9          142
109      9          222
110      0            0

In [9]:
# Add a new column named "Goals per Appearance" calculated by dividing "Goals" by "Appearances"
foot_ball['Goals per Appearance'] = foot_ball['Goals'] / foot_ball['Appearances']

# Display the first 5 rows of the updated dataset
foot_ball.head()

,Name,Jersey Number,Club,Position,Nationality,Age,Appearances,Wins,Losses,Goals,...,High Claims,Catches,Sweeper clearances,Throw outs,Goal Kicks,Yellow cards,Red cards,Fouls,Offsides,Goals per Appearance
0,Bernd Leno,1.0,Arsenal,Goalkeeper,Germany,28.0,64,28,16,0,...,26.0,17.0,28.0,375.0,489.0,2,0,0,NaN,0.00000
1,Matt Macey,33.0,Arsenal,Goalkeeper,England,26.0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,NaN,NaN
2,Rúnar Alex Rúnarsson,13.0,Arsenal,Goalkeeper,Iceland,25.0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,NaN,NaN
3,Héctor Bellerín,2.0,Arsenal,Defender,Spain,25.0,160,90,37,7,...,NaN,NaN,NaN,NaN,NaN,23,0,125,8.0,0.04375
4,Kieran Tierney,3.0,Arsenal,Defender,Scotland,23.0,16,7,5,1,...,NaN,NaN,NaN,NaN,NaN,2,0,9,0.0,0.06250

In [10]:
# Select and display a subset of the dataframe containing only the players from "Arsenal" club
arsenal_players = foot_ball[foot_ball['Club'] == 'Arsenal']
arsenal_players

,Name,Jersey Number,Club,Position,Nationality,Age,Appearances,Wins,Losses,Goals,...,High Claims,Catches,Sweeper clearances,Throw outs,Goal Kicks,Yellow cards,Red cards,Fouls,Offsides,Goals per Appearance
0,Bernd Leno,1.0,Arsenal,Goalkeeper,Germany,28.0,64,28,16,0,...,26.0,17.0,28.0,375.0,489.0,2,0,0,NaN,0.000000
1,Matt Macey,33.0,Arsenal,Goalkeeper,England,26.0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,NaN,NaN
2,Rúnar Alex Rúnarsson,13.0,Arsenal,Goalkeeper,Iceland,25.0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,NaN,NaN
3,Héctor Bellerín,2.0,Arsenal,Defender,Spain,25.0,160,90,37,7,...,NaN,NaN,NaN,NaN,NaN,23,0,125,8.0,0.043750
4,Kieran Tierney,3.0,Arsenal,Defender,Scotland,23.0,16,7,5,1,...,NaN,NaN,NaN,NaN,NaN,2,0,9,0.0,0.062500
5,William Saliba,4.0,Arsenal,Defender,France,19.0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0,NaN
6,Sokratis,5.0,Arsenal,Defender,Greece,32.0,44,21,11,3,...,NaN,NaN,NaN,NaN,NaN,18,0,56,1.0,0.068182
7,Rob Holding,16.0,Arsenal,Defender,England,25.0,41,25,9,0,...,NaN,NaN,NaN,NaN,NaN,8,0,32,0.0,0.000000
8,Shkodran Mustafi,20.0,Arsenal,Defender,Germany,28.0,99,52,26,7,...,NaN,NaN,NaN,NaN,NaN,28,0,117,7.0,0.070707
9,Calum Chambers,21.0,Arsenal,Defender,England,25.0,139,47,57,6,...,NaN,NaN,NaN,NaN,NaN,28,1,137,2.0,0.043165
10,David Luiz,23.0,Arsenal,Defender,Brazil,33.0,194,113,38,13,...,NaN,NaN,NaN,NaN,NaN,40,3,212,5.0,0.067010
11,Sead Kolasinac,31.0,Arsenal,Defender,Bosnia And Herzegovina,27.0,78,40,22,2,...,NaN,NaN,NaN,NaN,NaN,12,0,74,16.0,0.025641
12,Gabriel Magalhães,6.0,Arsenal,Defender,Brazil,22.0,2,2,0,1,...,NaN,NaN,NaN,NaN,NaN,0,0,3,0.0,0.500000
13,Mesut Özil,10.0,Arsenal,Midfielder,Germany,31.0,184,100,39,33,...,NaN,NaN,NaN,NaN,NaN,13,0,95,83.0,0.179348
14,Lucas Torreira,11.0,Arsenal,Midfielder,Uruguay,24.0,63,28,15,3,...,NaN,NaN,NaN,NaN,NaN,14,1,62,0.0,0.047619
15,Ainsley Maitland-Niles,15.0,Arsenal,Midfielder,England,23.0,54,26,16,1,...,NaN,NaN,NaN,NaN,NaN,6,2,35,1.0,0.018519
16,Mohamed Elneny,25.0,Arsenal,Midfielder,Egypt,28.0,47,29,10,0,...,NaN,NaN,NaN,NaN,NaN,7,1,24,2.0,0.000000
17,Joseph Willock,28.0,Arsenal,Midfielder,England,21.0,33,12,12,1,...,NaN,NaN,NaN,NaN,NaN,2,0,13,0.0,0.030303
18,Matteo Guendouzi,29.0,Arsenal,Midfielder,France,21.0,57,24,17,0,...,NaN,NaN,NaN,NaN,NaN,15,0,41,0.0,0.000000
19,Emile Smith Rowe,32.0,Arsenal,Midfielder,England,20.0,2,0,1,0,...,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0,0.000000
20,Granit Xhaka,34.0,Arsenal,Midfielder,Switzerland,27.0,132,70,33,8,...,NaN,NaN,NaN,NaN,NaN,35,2,196,2.0,0.060606
21,Bukayo Saka,7.0,Arsenal,Midfielder,England,19.0,28,11,7,1,...,NaN,NaN,NaN,NaN,NaN,6,0,22,13.0,0.035714
22,Dani Ceballos,8.0,Arsenal,Midfielder,Spain,24.0,26,14,6,0,...,NaN,NaN,NaN,NaN,NaN,1,0,21,0.0,0.000000
23,Alexandre Lacazette,9.0,Arsenal,Forward,France,29.0,99,46,28,39,...,NaN,NaN,NaN,NaN,NaN,11,0,127,62.0,0.393939
24,Pierre-Emerick Aubameyang,14.0,Arsenal,Forward,Gabon,31.0,87,43,25,55,...,NaN,NaN,NaN,NaN,NaN,4,1,30,55.0,0.632184
25,Nicolas Pépé,19.0,Arsenal,Forward,Cote D'Ivoire,25.0,33,15,9,5,...,NaN,NaN,NaN,NaN,NaN,4,0,14,4.0,0.151515
26,Reiss Nelson,24.0,Arsenal,Forward,England,20.0,20,10,5,1,...,NaN,NaN,NaN,NaN,NaN,1,0,8,4.0,0.050000
27,Eddie Nketiah,30.0,Arsenal,Forward,England,21.0,23,12,8,4,...,NaN,NaN,NaN,NaN,NaN,0,1,18,5.0,0.173913
28,Gabriel Martinelli,35.0,Arsenal,Forward,Brazil,19.0,14,3,3,3,...,NaN,NaN,NaN,NaN,NaN,1,0,9,2.0,0.214286
29,Willian,12.0,Arsenal,Forward,Brazil,32.0,236,137,47,37,...,NaN,NaN,NaN,NaN,NaN,21,1,131,33.0,0.156780

In [11]:
# Perform a filtering operation to display players who have scored more than 5 goals
high_scorers = foot_ball[foot_ball['Goals'] > 5]
high_scorers

,Name,Jersey Number,Club,Position,Nationality,Age,Appearances,Wins,Losses,Goals,...,High Claims,Catches,Sweeper clearances,Throw outs,Goal Kicks,Yellow cards,Red cards,Fouls,Offsides,Goals per Appearance
3,Héctor Bellerín,2.0,Arsenal,Defender,Spain,25.0,160,90,37,7,...,NaN,NaN,NaN,NaN,NaN,23,0,125,8.0,0.043750
8,Shkodran Mustafi,20.0,Arsenal,Defender,Germany,28.0,99,52,26,7,...,NaN,NaN,NaN,NaN,NaN,28,0,117,7.0,0.070707
9,Calum Chambers,21.0,Arsenal,Defender,England,25.0,139,47,57,6,...,NaN,NaN,NaN,NaN,NaN,28,1,137,2.0,0.043165
10,David Luiz,23.0,Arsenal,Defender,Brazil,33.0,194,113,38,13,...,NaN,NaN,NaN,NaN,NaN,40,3,212,5.0,0.067010
13,Mesut Özil,10.0,Arsenal,Midfielder,Germany,31.0,184,100,39,33,...,NaN,NaN,NaN,NaN,NaN,13,0,95,83.0,0.179348
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
544,Andriy Yarmolenko,7.0,West-Ham-United,Forward,Ukraine,30.0,34,10,16,7,...,NaN,NaN,NaN,NaN,NaN,5,0,25,9.0,0.205882
546,Sébastien Haller,22.0,West-Ham-United,Forward,France,26.0,34,9,18,7,...,NaN,NaN,NaN,NaN,NaN,1,0,49,19.0,0.205882
559,Rúben Neves,8.0,Wolverhampton-Wanderers,Midfielder,Portugal,23.0,75,30,23,6,...,NaN,NaN,NaN,NaN,NaN,17,0,66,0.0,0.080000
563,Leander Dendoncker,32.0,Wolverhampton-Wanderers,Midfielder,Belgium,25.0,59,26,15,6,...,NaN,NaN,NaN,NaN,NaN,6,0,43,1.0,0.101695
567,Raúl Jiménez,9.0,Wolverhampton-Wanderers,Forward,Mexico,29.0,78,32,23,32,...,NaN,NaN,NaN,NaN,NaN,7,0,81,52.0,0.410256